#!/usr/bin/env python3
"""Generate the deterministic progressive-disclosure catalog for `.llm/skills`."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from validate_skills import SKILLS_DIR, validate_library


INDEX_PATH = SKILLS_DIR / "index.md"


def render_index() -> str:
    metadata, errors = validate_library()
    if errors:
        raise ValueError("\n".join(errors))

    lines = [
        "# Skills Index",
        "",
        "> WARNING: Auto-generated by",
        "> `.llm/skills/manage-skills/scripts/generate_skills_index.py`. Do not edit manually.",
        "",
        "Agents should select a skill from its description, then load only that `SKILL.md` and the",
        "resources it directs them to read or run.",
        "",
        "## Available Skills",
        "",
        "<!-- markdownlint-disable MD013 -->",
        "",
    ]
    for skill in sorted(metadata, key=lambda item: item.path.relative_to(SKILLS_DIR).as_posix()):
        relative = skill.path.relative_to(SKILLS_DIR).as_posix()
        lines.append(f"- [{skill.title}]({relative}) (`{skill.name}`) — {skill.description}")
    lines.extend(["", "<!-- markdownlint-enable MD013 -->"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the catalog is stale")
    args = parser.parse_args()
    try:
        expected = render_index()
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1

    if args.check:
        if not INDEX_PATH.is_file() or INDEX_PATH.read_text(encoding="utf-8") != expected:
            print("Skills index is out of date; run generate_skills_index.py.", file=sys.stderr)
            return 1
        print("Skills index is up to date.")
        return 0

    if INDEX_PATH.is_file() and INDEX_PATH.read_text(encoding="utf-8") == expected:
        print("Skills index is already up to date.")
    else:
        INDEX_PATH.write_text(expected, encoding="utf-8")
        print("Generated .llm/skills/index.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
