#!/usr/bin/env bash
# generate-skills-index.sh - Generate deterministic, filename/path-ordered index for .llm/skills/*.md

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/.llm/skills"
INDEX_FILE="$SKILLS_DIR/index.md"

usage() {
    cat <<'EOF'
Usage:
  ./scripts/generate-skills-index.sh          # Generate/update .llm/skills/index.md
  ./scripts/generate-skills-index.sh --check  # Exit non-zero if index.md is stale/missing
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

CHECK_ONLY=false
if [ "${1:-}" = "--check" ]; then
    CHECK_ONLY=true
elif [ -n "${1:-}" ]; then
    echo "Unknown argument: $1" >&2
    usage >&2
    exit 2
fi

if [ ! -d "$SKILLS_DIR" ]; then
    echo "Skills directory not found: $SKILLS_DIR" >&2
    exit 1
fi

TMP_OUTPUT="$(mktemp)"
trap 'rm -f "$TMP_OUTPUT"' EXIT

{
    echo "# Skills Index"
    echo ""
    echo '> ⚠️ Auto-generated by `scripts/generate-skills-index.sh`. Do not edit manually.'
    echo ""
    echo "## Files"
    echo ""

    # Ordering contract:
    # - Entries are sorted by full file path with LC_ALL=C byte-wise collation.
    # - This keeps output deterministic across platforms and independent of title text.

    find "$SKILLS_DIR" -maxdepth 1 -type f -name '*.md' ! -name 'index.md' -print \
        | LC_ALL=C sort \
        | while IFS= read -r abs_path; do
            file_name="$(basename "$abs_path")"
            skill_title="$(awk '
                /^# Skill:/ {
                    title=$0
                    sub(/^# Skill:[[:space:]]*/, "", title)
                    print title
                    found=1
                    exit
                }
                END {
                    if (!found) {
                        print ""
                    }
                }
            ' "$abs_path")"

            if [ -n "$skill_title" ]; then
                echo "- [$skill_title](./$file_name)"
            else
                echo "- [$file_name](./$file_name)"
            fi
        done
} > "$TMP_OUTPUT"

if [ "$CHECK_ONLY" = true ]; then
    if [ ! -f "$INDEX_FILE" ]; then
        echo "Skills index is missing: .llm/skills/index.md"
        echo "Run: ./scripts/generate-skills-index.sh"
        exit 1
    fi

    if ! cmp -s "$TMP_OUTPUT" "$INDEX_FILE"; then
        echo "Skills index is out of date: .llm/skills/index.md"
        echo "Run: ./scripts/generate-skills-index.sh"
        exit 1
    fi

    echo "Skills index is up to date."
    exit 0
fi

if [ -f "$INDEX_FILE" ] && cmp -s "$TMP_OUTPUT" "$INDEX_FILE"; then
    echo "Skills index is already up to date."
else
    cp "$TMP_OUTPUT" "$INDEX_FILE"
    echo "Generated .llm/skills/index.md"
fi
