#!/usr/bin/env bash
# Generate a deterministic human-readable catalog from standardized SKILL.md metadata.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/.agents/skills"
INDEX_FILE="$SKILLS_DIR/index.md"

usage() {
    cat <<'EOF'
Usage:
  ./scripts/generate-skills-index.sh
  ./scripts/generate-skills-index.sh --check
EOF
}

CHECK_ONLY=false
case "${1:-}" in
    '') ;;
    --check) CHECK_ONLY=true ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
esac

[ -d "$SKILLS_DIR" ] || { printf 'Skills directory not found: %s\n' "$SKILLS_DIR" >&2; exit 1; }

TMP_OUTPUT=$(mktemp)
trap 'rm -f "$TMP_OUTPUT"' EXIT

{
    printf '<!-- markdownlint-disable MD013 MD044 -->\n\n'
    printf '# Agent Skills Index\n\n'
    printf '> Generated by `scripts/generate-skills-index.sh` from `SKILL.md` frontmatter.\n\n'
    printf 'Codex discovers these packages directly from `.agents/skills`; this catalog is for human navigation.\n\n'
    find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -type f -name SKILL.md -print \
        | LC_ALL=C sort \
        | while IFS= read -r skill_file; do
            relative=${skill_file#"$SKILLS_DIR/"}
            name=$(sed -n '2s/^name:[[:space:]]*//p' "$skill_file" | tr -d '\r')
            description=$(sed -n '3s/^description:[[:space:]]*//p' "$skill_file" | tr -d '\r')
            printf -- '- [`$%s`](./%s) — %s\n' "$name" "$relative" "$description"
        done
} > "$TMP_OUTPUT"

if [ "$CHECK_ONLY" = true ]; then
    [ -f "$INDEX_FILE" ] || { printf 'Skills index is missing: .agents/skills/index.md\n' >&2; exit 1; }
    cmp -s "$TMP_OUTPUT" "$INDEX_FILE" || {
        printf 'Skills index is out of date. Run: ./scripts/generate-skills-index.sh\n' >&2
        exit 1
    }
    printf 'Skills index is up to date.\n'
elif [ -f "$INDEX_FILE" ] && cmp -s "$TMP_OUTPUT" "$INDEX_FILE"; then
    printf 'Skills index is already up to date.\n'
else
    cp "$TMP_OUTPUT" "$INDEX_FILE"
    printf 'Generated .agents/skills/index.md\n'
fi
